repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.2.5.a10
    hooks:
      - id: cfn-lint-rc
  - repo: https://github.com/aws-cloudformation/rain
    rev: v1.10.0
    hooks:
      - id: cfn-format
