repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.83.8
    hooks:
    -   id: cfn-lint-rc
-   repo: https://github.com/aws-cloudformation/rain
    rev: v1.7.5
    hooks:
    -   id: cfn-format
